sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t honzirek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true honzirek/docker-react npm run test